[build]
  command = "node fix-renderer.js"
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
